### ISSUE TITLE
[BUG] - showAxiom: unhandled case for entity: Concept and axiom: KeyAxiom

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/oml#66]
## Description

See: https://github.com/NicolasRouquette/description-graphs/tree/68fa02ce97fe28850243680e01279c1e6d76be2b

## Steps to Reproduce
- [ ] https://github.com/NicolasRouquette/description-graphs/tree/68fa02ce97fe28850243680e01279c1e6d76be2b
- [ ] open diagram for `hand` in OML Luxor
- [ ] exception:

```
[Error - 5:19:52 PM] exception: java.lang.IllegalArgumentException: showAxiom: unhandled case for entity: Concept and axiom: KeyAxiom
	at io.opencaesar.oml.dsl.ide.diagram.OmlDiagramViewGenerator.showAxiom(OmlDiagramViewGenerator.java:344)
	at io.opencaesar.oml.dsl.ide.diagram.OmlDiagramViewGenerator.lambda$generate$1(OmlDiagramViewGenerator.java:90)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.opencaesar.oml.dsl.ide.diagram.OmlDiagramViewGenerator.lambda$generate$2(OmlDiagramViewGenerator.java:90)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at io.opencaesar.oml.dsl.ide.diagram.OmlDiagramViewGenerator.generate(OmlDiagramViewGenerator.java:89)
	at org.eclipse.sprotty.xtext.LanguageAwareDiagramServer.generate(LanguageAwareDiagramServer.java:102)
	at org.eclipse.sprotty.xtext.ls.DiagramUpdater.lambda$null$3(DiagramUpdater.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.eclipse.sprotty.xtext.ls.DiagramUpdater.lambda$doUpdateDiagrams$4(DiagramUpdater.java:133)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$null$0(LanguageServerImpl.java:1094)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:438)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$doRead$1(LanguageServerImpl.java:1093)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:66)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```

## Expected Behavior
A clear and concise description of what should be the expected behavior.

no exception and a nice oml diagram.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
If applicable, add screenshots to help illustrate the issue.

**Comment by melaasar** [comment]
Cannot reproduce this exception and I see the OML diagram with Luxor 0.9.2. Please verify and if still happening, feel free to reopen.
