### ISSUE TITLE
[BUG] - Cannot build on windows.

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/oml#78]
## Steps to Reproduce
- [ ] Clone oml on windows
- [ ] `.\gradlew build`

## Expected Behavior
A clear and concise description of what should be the expected behavior.

The build should be successful.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

There are lots of errors:

```
PS C:\opt\local\github.opencaesar\oml> git log -n1
commit 55f7b999b687fdd3c39c5df3a538fd7501952df9 (HEAD -> master, origin/master, origin/HEAD)
Author: Paul Gaspardo <gaspardo@jpl.nasa.gov>
Date:   Wed Jul 28 15:29:00 2021 -0700

    Fix OmlSearch.findIsKindOf() (#77)
PS C:\opt\local\github.opencaesar\oml> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
PS C:\opt\local\github.opencaesar\oml> .\gradlew build --stacktrace

> Task :io.opencaesar.oml:generateXtext FAILED
ERROR:EDiagnosticChain cannot be resolved to a type. (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 53 column : 30)
ERROR:EMap cannot be resolved to a type. (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 53 column : 60)
ERROR:org.eclipse.emf.ecore.EDiagnosticChain cannot be resolved. (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 35 column : 8)
ERROR:org.eclipse.emf.ecore.EMap cannot be resolved. (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 36 column : 8)
ERROR:Type mismatch: cannot convert from Object to DiagnosticChain (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 54 column : 49)
ERROR:Type mismatch: cannot convert from Object<?, ?> to Map<Object, Object> (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 54 column : 62)
ERROR:Type mismatch: cannot convert from SeparatorKind to String (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 138 column : 20)
ERROR:Type mismatch: cannot convert from Object to String (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 226 column : 26)
ERROR:Ecore cannot be resolved. (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 5 column : 2)
ERROR:GenModel cannot be resolved. (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 9 column : 2)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 53 column : 0)
ERROR:The generic type associated with the 'EJavaObject' classifier must not have 2 argument(s) when the classifier has 0 type parameter(s) (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 53 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 112 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 137 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 125 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 133 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 223 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 231 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 221 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 337 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 341 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 345 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 349 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 353 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 357 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 361 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 406 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 515 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 520 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 995 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 999 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 1534 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 1556 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 1560 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 1573 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 1621 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 1625 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 1640 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 1659 column : 0)
ERROR:A generic type in this context must refer to a classifier or a type parameter (file:/C:/opt/local/github.opencaesar/oml/io.opencaesar.oml/src/io/opencaesar/oml/Oml.xcore line : 1670 column : 0)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':io.opencaesar.oml:generateXtext'.
> Xtext validation failed, see build log for details.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':io.opencaesar.oml:generateXtext'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:200)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:198)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:179)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.GradleException: Xtext validation failed, see build log for details.
        at org.xtext.gradle.builder.XtextGradleBuilder.build(XtextGradleBuilder.java:196)
        at org.xtext.gradle.tasks.XtextGenerate.generate(XtextGenerate.java:166)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskInputsTaskAction.doExecute(IncrementalTaskInputsTaskAction.java:47)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:555)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:540)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:523)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:271)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:260)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$0(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:67)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:36)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:49)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:34)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:43)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:44)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:54)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:38)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:42)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:159)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:72)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:43)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:44)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:33)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:85)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:94)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:79)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:187)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:179)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
```

## Relevant screenshots
If applicable, add screenshots to help illustrate the issue.

**Comment by melaasar** [comment]
Try to delete the .gradle folder and build again. Let me know if you still get the same error.
